language: scala

scala:
  - 2.13.3

jdk:
  - oraclejdk11

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.26.2

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

cache:
  directories:
    - docker-cache
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt

jobs:
  include:
    - stage: test
      script: ./.cicd/test.sh
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: integration test
      script:
        - ./.cicd/integration-test.sh
    - stage: benchmarks
      script:
        - ./.cicd/benchmarks.sh
#    - stage: build
#      script: ./.cicd/build.sh
#    - stage: doc
#      script: ./.cicd/doc.sh
#    - stage: release
#      script: ./.cicd/release.sh
#    - stage: publish
#      script: ./.cicd/publish.sh

notifications:
  email: false
