language: scala

scala:
  - 2.13.3

jdk:
  - openjdk11

services:
  - docker

cache:
  directories:
    - docker-cache

jobs:
  include:
    - stage: test
      script: ./.cicd/test.sh
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: integration test
      script: ./.cicd/integration-test.sh
#    - stage: build
#      script: ./.cicd/build.sh
#    - stage: doc
#      script: ./.cicd/doc.sh
#    - stage: release
#      script: ./.cicd/release.sh
#    - stage: publish
#      script: ./.cicd/publish.sh

