language: scala

scala:
  - 2.13.3

jdk:
  - openjdk11

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

cache:
  directories:
    - docker-cache

jobs:
  include:
    - stage: test
      script: ./.cicd/test.sh
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: integration test
      script: docker-compose --version && docker --version && ./.cicd/integration-test.sh
#    - stage: build
#      script: ./.cicd/build.sh
#    - stage: doc
#      script: ./.cicd/doc.sh
#    - stage: release
#      script: ./.cicd/release.sh
#    - stage: publish
#      script: ./.cicd/publish.sh

