version: '3.8'

services:

  localstack:
    image: localstack/localstack
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      # Declare which aws services will be used in localstack
      - SERVICES=sqs,s3
      - DEBUG=1
      # These variables are needed for localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=andromedaAccessKeyId
      - AWS_SECRET_ACCESS_KEY=andromedaSecretAccessKey
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - /tmp/localstack:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./localstack_setup.sh:/docker-entrypoint-initaws.d/localstack_setup.sh