addSbtPlugin("ch.epfl.scala"               % "sbt-scalajs-bundler" % "0.21.0")
addSbtPlugin("com.eed3si9n"                % "sbt-assembly"        % "0.14.10")
addSbtPlugin("com.eed3si9n"                % "sbt-buildinfo"       % "0.11.0")
addSbtPlugin("com.lightbend.sbt"           % "sbt-javaagent"       % "0.1.6")
addSbtPlugin("com.typesafe.sbt"            % "sbt-git"             % "1.0.2")
addSbtPlugin("com.github.sbt"              % "sbt-native-packager" % "1.9.11")
addSbtPlugin("io.spray"                    % "sbt-revolver"        % "0.9.1")
//addSbtPlugin("org.jmotor.sbt"              % "sbt-dependency-updates" % "1.2.2")
addSbtPlugin("org.scala-js"                % "sbt-scalajs"         % "1.15.0")
addSbtPlugin("org.scalameta"               % "sbt-mdoc"            % "2.3.6")
addSbtPlugin("org.scalameta"               % "sbt-scalafmt"        % "2.4.6")
// addSbtPlugin("org.scoverage"               % "sbt-scoverage"       % "2.0.6")
addSbtPlugin("pl.project13.scala"          % "sbt-jmh"             % "0.4.3")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter"       % "1.0.0-beta40")
addDependencyTreePlugin
