version: '3.8'

services:

  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - 9324:9324
      # - 9325:9325
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
      - ./data:/data