version: '2'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - "TZ=Europe/Madrid"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    ports:
      - "5432:5432"
    volumes:
      - "./script:/docker-entrypoint-initdb.d"

  cassandra:
    image: cassandra:3
    container_name: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - "CASSANDRA_CLUSTER_NAME=OUR_DOCKERIZED_CASSANDRA_SINGLE_NODE_CLUSTER"