version: '3.8'
services:

  # I N F R A S T R U C T U R E
  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    user: ${UID}:${GID} # docker run ... --user="$(id -u):$(id -g)" neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/accounttest
    volumes:
      - ./data:/data
      - ./logs:/logs
      - /tmp/neo4j/import:/var/lib/neo4j/import
      - /tmp/neo4j/plugins:/plugins
    restart: always

  grpcui:
    container_name: grpcui
    image: fullstorydev/grpcui
    command: -plaintext -protoset /protos/descriptor.protoset "host.docker.internal:9999"
    ports:
      - 8080:8080
    volumes:
      - ./:/protos
    restart: always

  grpcurl:
    container_name: grpcurl
    image: fullstorydev/grpcurl
    command: |
      -protoset /protos/descriptor.protoset
      -d '{"startLabel": "PERSON", "limit": 2, "relationshipQuery": {"direction": "BOTH"}}'
      -plaintext "host.docker.internal:9999"
      Service/Method
    volumes:
      - ./:/protos
    restart: always