version: '3.7'

services:

  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=s3,lambda,cloudWatch
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      #- DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      #- DOCKER_HOST=unix:///var/run/docker.sock
      #- HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"