version: '3.8'
services:

  # I N F R A S T R U C T U R E
  grpcui:
    container_name: grpcui
    image: fullstorydev/grpcui
    command: -plaintext "host.docker.internal:9999"
    ports:
      - 8080:8080
    restart: always