version: '3.8'

services:

  localstack:
    image: localstack/localstack:1.0.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,cloudwatch
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      #- DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      #- DOCKER_HOST=unix:///var/run/docker.sock
      #- HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"