CREATE TABLE IF NOT EXISTS "VERTEXES"
(
    "TENANT_ID" BIGINT NOT NULL,
    "ASSET_ID"  BIGINT NOT NULL,
    "ID"        BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
);
CREATE UNIQUE INDEX IF NOT EXISTS "tenant_asset_index" on "VERTEXES" ("TENANT_ID", "ASSET_ID");

CREATE TABLE IF NOT EXISTS "EDGES"
(
    "START_VERTEX_ID" BIGINT  NOT NULL,
    "END_VERTEX_ID"   BIGINT  NOT NULL,
    "META_MODEL"      VARCHAR NOT NULL,
    "ID"              BIGINT  NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE UNIQUE INDEX IF NOT EXISTS "start_end_vertex_index" on "EDGES" ("START_VERTEX_ID", "END_VERTEX_ID");

ALTER TABLE "EDGES"
    add constraint IF NOT EXISTS "START_VERTEX_FK" foreign key ("START_VERTEX_ID") references "VERTEXES" ("ID") on update NO ACTION on delete NO ACTION;

ALTER TABLE "EDGES"
    add constraint IF NOT EXISTS "END_VERTEX_FK" foreign key ("END_VERTEX_ID") references "VERTEXES" ("ID") on update NO ACTION on delete NO ACTION;
